src/base_site/urls.py
"""
Copyright 2015-2019 Mathieu Courcelles
CAPCA - Center for Advanced Proteomics and Chemogenomics Analyses
Pierre Thibault's lab
IRIC - Universite de Montreal

AGPL-3.0-or-later

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

"""



# Import standard libraries

# Import Django related libraries
from django.contrib.auth.views import (PasswordChangeView,
                                       PasswordChangeDoneView)
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.storage import staticfiles_storage
from django.template.response import TemplateResponse
from django.views.generic.base import RedirectView

from base_site.views.registration_custom import RegistrationView

# Third party libraries
from ajax_select import urls as ajax_select_urls

# Import project libraries
from .forms import PasswordChangeFormCustom, RegistrationFormCustom
import mhc_pipeline.views.base_site
from .views.base_site import alive, server_secure_media


def handler500(request):
    """500 error handler which includes ``request`` in the context.

    Templates: `500.html`
    Context: None
    """

    context = {'request': request}

    template_name = '500.html'  # You need to create a 500.html template.
    return TemplateResponse(request, template_name, context, status=500)


urlpatterns = [

    # My apps
    url(r'mhc_pipeline/', include('mhc_pipeline.urls')),

    url(r'session_security/', include('session_security.urls')),

    # Dashboard
    url(r'^$', mhc_pipeline.views.base_site.home, name='home'),

    url(r'^accounts/password/change/$',  # hijack password_change's url
        PasswordChangeView.as_view(form_class=PasswordChangeFormCustom),
        name="password_change"),

    url(r'^password/change/done/$',
        PasswordChangeDoneView.as_view(),
        name='password_change_done'),

    url(r'^accounts/', include('registration.backends.default.urls')),

    url(r'^favicon.ico$',
        RedirectView.as_view(url=staticfiles_storage.url('img/favicon.ico'),
                             permanent=False),
        name="favicon"),

    # Admin
    url(r'^grappelli/', include('grappelli.urls')),  # grappelli URLS
    url(r'^admin/', admin.site.urls),
    url(r'^admin/defender/', include('defender.urls')),  # defender admin


    # Authentication
    url(r'^accounts/register/$',
        RedirectView.as_view(url='/accounts/register/closed/', permanent=False),
        name='registration_closed'),

    url(r'^accounts/register_mapdp/$',
        RegistrationView.as_view(form_class=RegistrationFormCustom),
        name='registration_register'),

    url(
        r'^accounts/register_iric/email/(?P<user_pk>\d+)/(?P<activation_key>\w+)/$',
        RegistrationView.transmit_activation_mail,
        name='registration_email'),

    url(r'^alive/', alive),
    url(r'^hc/', include('health_check.urls')),

    url(r'^media/(?P<url>.+)$', server_secure_media),

    url(r'^ajax_select/', include(ajax_select_urls)),
]


# Local only
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

    import debug_toolbar

    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

src/mhc_pipeline/models.py
"""
Copyright 2015-2020 Mathieu Courcelles
CAPCA - Center for Advanced Proteomics and Chemogenomics Analyses
Pierre Thibault's lab
IRIC - Universite de Montreal

AGPL-3.0-or-later

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

"""


# Import standard libraries
from collections import namedtuple
from datetime import datetime
import json
import os
import re
from pathlib import Path
from pytz import timezone

# Import Django related libraries
from django.conf import settings
from django.contrib.auth.models import User
from django.core.cache import caches
from django.core.exceptions import ObjectDoesNotExist
from django.urls import reverse
from django.core.validators import (MaxValueValidator,
                                    MinValueValidator)
from django.db import models
from django.db.models.signals import (post_save,
                                      pre_save)
from django.dispatch import receiver
from django.utils.functional import cached_property

# Third party libraries
from chunked_upload.models import ChunkedUpload
from guardian.shortcuts import get_objects_for_user


# Import project libraries
from .library.permission import get_if_permission


# Helper methods
def model_path(instance, file_name):
    """
    Returns class name of the instance for file upload path
    :param instance: Model instance
    :param file_name: String
    :return: String
    """

    return os.path.join(instance.__class__.__name__, file_name)


STATUSES = (
    ('', ''),
    ('pending', 'Pending'),
    ('started', 'Started'),
    ('success', 'Success'),
    ('failed', 'Failed'),
)


class BaseModel(models.Model):
    """
    This class provides user/time details for object creation, modifications
    and deletion.
    """

    created_at = models.DateTimeField(auto_now_add=True)

    created_by = models.ForeignKey(User, on_delete=models.PROTECT,
                                   related_name='+')

    modified_at = models.DateTimeField(auto_now=True)

    modified_by = models.ForeignKey(User, on_delete=models.PROTECT,
                                    related_name='+')

    trashed = models.BooleanField(default=False)

    class Meta:
        abstract = True


class BiologicalSampleManager(models.Manager):
    """
    This manager class provides selection of instances with the 'view'
    permission.
    """

    def for_user(self, user, related=False):
        """
        Selects instances with the 'view' permission.
        :param user: User instance
        :param related: Query users that created or modified the instance.
        :return: Queryset
        """

        klass = self.get_queryset().filter(trashed=0)

        if related:
            klass = klass.select_related('created_by', 'modified_by')

        return get_objects_for_user(user, 'mhc_pipeline.view_biologicalsample',
                                    klass=klass)


class BiologicalSample(BaseModel):
    """
    This model describes the biological sample analyzed and stored.
    """

    identifier = models.CharField(help_text='Identifier labelled on the '
                                            'biological sample.',
                                  max_length=20,
                                  unique=True,
                                  verbose_name="Identifier")

    short_description = models.CharField(blank=True,
                                         max_length=100,
                                         null=True)

    TAXID_CHOICES = dict()
    TAXID_CHOICES[9606] = 'Homo sapiens'
    TAXID_CHOICES[10090] = 'Mus musculus'

    taxonomy_identifier = models.IntegerField(choices=TAXID_CHOICES.items(),
                                              default=9606,
                                              name='Species')

    cell_type = models.CharField(max_length=100,
                                 blank=True,
                                 null=True)

    tissue = models.CharField(max_length=100,
                              blank=True,
                              null=True)

    organ = models.CharField(max_length=100,
                             blank=True,
                             null=True)

    objects = BiologicalSampleManager()

    def __str__(self):
        """
        Object text representation
        :return: String
        """
        return 'Id: %s' % self.identifier

    def get_absolute_url(self):
        """
        Define a get_absolute_url() method to tell Django how to calculate the
        canonical URL for an object.
        :return: String
        """

        return reverse('biological_sample:view', kwargs={'pk': self.pk})


class FilterManager(models.Manager):
    """
    This manager class provides selection of instances with specific permission.
    """

    def for_user(self, user):
        """
        Selects instances with the 'view' permission.
        :param user: User instance
        :return: Queryset
        """

        return get_objects_for_user(user, 'mhc_pipeline.view_filter',
                                    klass=self.get_queryset().filter(trashed=0),
                                    # with_superuser=False
                                    )

    def visible_for_user(self, user):
        """
        Selects instances with the 'visible' permission.
        :param user: User instance
        :return: Queryset
        """

        return get_objects_for_user(user, 'mhc_pipeline.visible_filter',
                                    klass=self.get_queryset().filter(trashed=0),
                                    with_superuser=False
                                    )


class Filter(BaseModel):
    """
    This model stores a JSON representation of parameters used to filter
    identified peptides.
    """

    name = models.CharField(max_length=1000)

    json_values = models.TextField()

    objects = FilterManager()

    class Meta:
        permissions = (
            ('visible_filter', 'Can show/hide filter'),
        )

    def __str__(self):
        """
        Object text representation
        :return: String
        """

        return self.name

    def get_absolute_url(self):
        """
        Define a get_absolute_url() method to tell Django how to calculate the
        canonical URL for an object.

        This is now a true absolute url but a hack to redirect to the right view.

        :return: String
        """

        return reverse('filter:list')


class LockModel(models.Model):
    """
    This model is used to prevent concurrent writing to models while inserting
    new data sets.
    """

    model = models.CharField(max_length=100, unique=True)

    timestamp = models.DateTimeField(auto_now=True)


class MHCSample(models.Model):
    """
    This model contains specific details related to MHC samples.
    """

    biological_sample = models.ForeignKey(BiologicalSample,
                                          on_delete=models.PROTECT)

    group = models.CharField(blank=True,
                             max_length=50,
                             null=True)

    GENDER_CHOICES = (
        ('F', 'Female'),
        ('M', 'Male')
    )

    gender = models.CharField(blank=True,
                              choices=GENDER_CHOICES,
                              max_length=1,
                              null=True)


class FileSet(BaseModel):
    """
    This model defines file sets of with files specific type.
    """

    name = models.CharField(max_length=150)

    SET_CLASS_CHOICES = dict()
    # SET_CLASS_CHOICES[1] = None
    SET_CLASS_CHOICES['LC-MS'] = 2
    SET_CLASS_CHOICES['Fasta'] = 3
    SET_CLASS_CHOICES['PEAKS - mzIdentML 1.1'] = 4
    SET_CLASS_CHOICES['PEAKS - features'] = 5
    SET_CLASS_CHOICES['MaxQuant'] = 6
    SET_CLASS_CHOICES['Comet'] = 7
    SET_CLASS_CHOICES['BAM'] = 8

    choices = ((v, k) for k, v in SET_CLASS_CHOICES.items())
    set_class = models.IntegerField(choices=choices)

    locked = models.BooleanField(default=False)

    FILE_SET = dict()
    FILE_SET['LC-MS'] = {'dir': settings.MS_DIR,
                         'extensions': ('.raw',),
                         'allowed_groups': ('ms',)}

    comet_note = 'Please select one .mzid (mzIdenML 1.1) file and at least ' \
                 'one .mgf.'

    FILE_SET['Comet'] = {'dir': settings.MS_DIR,
                         'extensions': ('.mzid', '.mgf'),
                         'allowed_groups': ('ms',),
                         'note': comet_note}

    FILE_SET['Fasta'] = {'dir': os.path.join(settings.MEDIA_ROOT, 'Fasta'),
                         'extensions': ('.fa', '.fasta', '.zip'),
                         'allowed_groups': ('ms', 'upload')}
    FILE_SET['BAM'] = {'dir': os.path.join(settings.MEDIA_ROOT, 'BAM'),
                       'extensions': ('.bam',),
                       'allowed_groups': ('upload',)}
    peaks_note = 'Please select one .mzid (mzIdenML 1.1) file and at least ' \
                 'one .mgf generated by PEAKS for Scaffold. When exporting ' \
                 'from PEAKS, set peptides score, proteins score and ' \
                 'unique peptide to 0, check "Show Decoy Hits" in ' \
                 'Windows/Preferences/Display Options and select "Show all"' \
                 ' in Protein section.'

    FILE_SET['PEAKS - mzIdentML 1.1'] = {'dir': settings.MS_DIR,
                                         'extensions': ('.mzid', '.mgf'),

src/mhc_pipeline/views/base_site.py
"""
Copyright 2015-2023 Mathieu Courcelles
CAPCA - Center for Advanced Proteomics and Chemogenomics Analyses
Pierre Thibault's lab
IRIC - Universite de Montreal

AGPL-3.0-or-later

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

"""



# Import standard libraries
import re

# Import Django related libraries
from django.contrib.auth.decorators import login_required
from django.core.cache import cache
from django.shortcuts import render


# Third party libraries
import feedparser

# Import project libraries
from ..models import (BiologicalSample,
                      File,
                      New,
                      Peptide,
                      UniquePeptide)


# Create your views here.


@login_required
def home(request):


    publications = cache.get('publications')

    if publications is None:

        publications = list()

        try: 

            d = feedparser.parse(
                'https://pubmed.ncbi.nlm.nih.gov/rss/search/1hwQrn1DrkWVI_4yWI3eP1F_nsEn5cVJVHSHuZ_52bghV3Agvz/')

            for entry in d['entries'][:2]:

                entry_mod = f'<p><b>{entry.title}</b></p>{entry.content[0]["value"]}'

                publications.append(entry_mod)

                cache.set('publications', publications, 60 * 60 * 24 * 7)
        
        except URLError:
            pass


    # Stats
    biological_sample_count = cache.get('biological_sample_count')

    if biological_sample_count is None:

        biological_sample_count = BiologicalSample.objects.filter(trashed=False).count()
        cache.set('biological_sample_count', biological_sample_count, 60 * 60 * 24 * 7)

    file_count = cache.get('file_count')

    if file_count is None:

        file_count = File.objects.count()
        cache.set('file_count', file_count, 60 * 60 * 24 * 7)

    unique_peptide_count = cache.get('unique_peptide_count')

    if unique_peptide_count is None:
        unique_peptide_count = UniquePeptide.objects.count()
        cache.set('unique_peptide_count', unique_peptide_count, 60 * 60 * 24 * 7)

    msms_count = cache.get('msms_count')

    if msms_count is None:

        msms_count = Peptide.objects.count()
        cache.set('msms_count', msms_count, 60 * 60 * 24 * 7)

    context = {
        'biological_sample_count':  biological_sample_count,
        'file_count': file_count,
        'msms_count': msms_count,
        'unique_peptide_count': unique_peptide_count,

        'news': New.objects.select_related('created_by', 'modified_by').all()[:5],
        'publications': publications,
    }

    return render(request, 'mhc_pipeline/base_site/home.html', context)

src/mhc_pipeline/templates/mhc_pipeline/biological_sample/experiment_details_tab.html
{% load crispy_forms_tags %}
{% load form_tags %}

<div class="row">

    <div class="col-md-12">

        <!-- Experiment details box -->
        <div class="box box-solid">

            <div class="box-header with-border">
                {% if obj.change_permission %}
                <div class="pull-right">
                    <a href="{% url 'biological_sample:experiment_details_create' obj.pk %}"
                       id="id_experiment_details_add_link">
                        <i class="fa fa-plus fa-lg" title="Add"></i></a>
                    &nbsp;
                </div>
                {% endif %}
            </div>
            <!-- /.box-header -->

            <div class="box-body">
                <div class="box-group" id="accordion">
                    <!-- we are adding the .panel class so bootstrap.js collapse plugin detects it -->
                    {% for details in experiment_details %}
                    <div class="panel box box-primary">
                        <div class="box-header with-border">
                            <h4 class="box-title">
                                <a data-toggle="collapse"
                                   data-parent="#accordion"
                                   href="#collapseED{{ forloop.counter }}">
                                    {{ details.name }}
                                </a>
                            </h4>

                        </div>
                        <div id="collapseED{{ forloop.counter }}"
                             class="panel-collapse collapse">
                            <div class="box-body">
                                {% if obj.change_permission %}
                                {% for form in details|experiment_details_form %}
                                {% crispy form %}
                                {% endfor %}
                                {% else %}
                                {% for form in details|experiment_details_form_no_perm %}
                                {% crispy form %}
                                {% endfor %}
                                {% endif %}
                            </div>
                        </div>
                    </div>

                    {% endfor %}

                </div>
            </div>
            <!-- /.box-body -->
        </div>
        <!-- /.box -->
    </div>
    <!-- /.col -->
</div>
<!-- /.row -->

src/mhc_pipeline/templates/mhc_pipeline/biological_sample/list.html
{% extends 'mhc_pipeline/base_site/list.html' %}


{% block list_table %}
<thead>
    <tr>
        <th></th>
        <th>Identifier</th>
        <th>Species</th>
        <th>Cell type</th>
        <th>Organ</th>
        <th>Created by</th>
        <th>Modified by</th>
        <th>Created on</th>
        <th>Modified on</th>
    </tr>
</thead>

<tbody>
    {% for sample in samples %}
    <tr>
        <td><a href="{% url 'biological_sample:view' sample.pk %}"><i
                class="glyphicon glyphicon-eye-open fa-1d5x" title="View"></i></a>
        </td>
        <td>{{ sample.identifier }}</td>
        <td>{{ sample.get_Species_display }}</td>
        <td>{{ sample.cell_type }}</td>
        <td>{{ sample.organ }}</td>
        <td>{{ sample.created_by }}</td>
        <td>{{ sample.modified_by }}</td>
        <td>{{ sample.created_at|date:"Y/m/d" }}</td>
        <td>{{ sample.modified_at|date:"Y/m/d" }}</td>
    </tr>
    {% endfor %}
</tbody>
{% endblock %}



{% block page_js %}
<!-- page script -->
<script>
      $(function () {
        $('#list_table').DataTable({
          "paging": true,
          "lengthChange": true,
          "searching": true,
          "ordering": true,
          "order": [[ 8, "dsc" ]],
          "info": true,
          "autoWidth": false,
          "pageLength": 20,
        });
      });

function onElementHeightChange(elm, callback){

	var lastHeight = elm.clientHeight, newHeight;
	(function run(){
		newHeight = elm.clientHeight;
		if( lastHeight != newHeight )
			callback();
		lastHeight = elm.clientHeight;

        if( elm.onElementHeightChangeTimer )
          clearTimeout(elm.onElementHeightChangeTimer);

		elm.onElementHeightChangeTimer = setTimeout(run, 200);
	})();
}


onElementHeightChange(document.body, function(){
  //alert('Body height changed');

  //Get window height and the wrapper height
      var neg = $('.main-header').outerHeight() + $('.main-footer').outerHeight();
      var window_height = $(window).height();
      //alert(window_height);
      //alert(document.documentElement.scrollHeight);
      window_height = document.documentElement.scrollHeight + 40;
      var sidebar_height = $(".sidebar").height();
      //Set the min-height of the content and sidebar based on the
      //the height of the document.

      if ($("body").hasClass("fixed")) {
        $(".content-wrapper, .right-side").css('min-height', window_height - $('.main-footer').outerHeight());
      } else {
        var postSetWidth;
        if (window_height >= sidebar_height) {
          $(".content-wrapper, .right-side").css('min-height', window_height - neg);
          postSetWidth = window_height - neg;
        } else {
          $(".content-wrapper, .right-side").css('min-height', sidebar_height);
          postSetWidth = sidebar_height;
        }

        //Fix for the control sidebar height
        var controlSidebar = $($.AdminLTE.options.controlSidebarOptions.selector);
        if (typeof controlSidebar !== "undefined") {
          if (controlSidebar.height() > postSetWidth)
            $(".content-wrapper, .right-side").css('min-height', controlSidebar.height());
        }

      }
});

</script>
{% endblock %}

src/mhc_pipeline/templates/mhc_pipeline/biological_sample/plots_state.html
{% if state != 'success' %}
<div class="col-sm-12">
{{ state|capfirst }}

{% if state == 'started' %}
<i class="fa fa-spinner fa-spin"></i>
{% endif %}
</div>


{% else %}

    {% for name in plots %}
    <div id="{{ name }}" class="col-sm-6">
        <a href="{% url 'biological_sample:plot_data' pk tax_id name %}"
        title="CSV table ({{ name }})"><i class="fa fa-table"></i></a>
    </div>

    <script>
    fetch('{% url 'biological_sample:plot' pk tax_id name %}')
    .then(function(response) { return response.json(); })
    .then(function(item) { Bokeh.embed.embed_item(item, "{{ name }}"); })
    </script>
    {% endfor %}

{% endif %}

src/mhc_pipeline/templates/mhc_pipeline/biological_sample/view.html
{% extends 'content.html' %}
{% load static %}

{% block content %}

<div class="row">
    <div class="col-sm-6">
        <!-- Description box -->
        <div class="box">
            <div class="box-header with-border">

                <h3 class="box-title">
                    <i class="fa fa-list"></i>&nbsp;&nbsp;
                    Description</h3>

                <div class="pull-right">
                    {% if obj.change_permission %}
                    <a href="{% url 'biological_sample:edit' obj.pk %}"
                       id="id_link_biological_sample_edit">
                        <i class="fa fa-pencil fa-lg" title="Edit"></i>
                    </a>
                    {% endif %}
                    &nbsp;&nbsp;&nbsp;&nbsp;
                    {% if obj.delete_permission %}
                    <a href="{% url 'biological_sample:trash' obj.pk 'false'%}"
                    id="id_biological_sample_trash">
                        <i class="fa fa-trash fa-lg" title="Trash"></i>
                    </a>
                    {% endif %}
                    &nbsp;
                </div>

            </div>
            <!-- /.box-header -->

            <div class="box-body">
                <dl class="dl-horizontal">
                    <dt>Identifier</dt>
                    <dd>{{ obj.identifier }}</dd>
                    <dt>Short description</dt>
                    <dd>{{ obj.short_description }}</dd>
                    <dt>Species</dt>
                    <dd>{{ obj.get_Species_display }}</dd>
                    <dt>Cell type</dt>
                    <dd>{{ obj.cell_type }}</dd>
                    <dt>Tissue</dt>
                    <dd>{{ obj.tissue }}</dd>
                    <dt>Organ</dt>
                    <dd>{{ obj.organ }}</dd>
                </dl>
            </div>
            <!-- /.box-body -->

            <div class="box-footer">
            </div>
            <!-- /.box-footer-->
        </div>
        <!-- /.box -->
    </div>
    <!-- /.col -->

    {% include 'mhc_pipeline/permission/tabs.html' %}

</div>
<!-- /.row -->



<div class="row">
    <div class="col-sm-6">
        <!-- MHC sample details box -->
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">
                    <i class="fa fa-list"></i>&nbsp;&nbsp;
                    MHC sample details</h3>

                <div class="pull-right">
                    {% if obj.change_permission %}
                    <a href="{% url 'biological_sample:mhc_details' obj.pk %}"
                       id="id_mhc_sample_link">
                        <i class="fa fa-pencil fa-lg" title="Edit"></i>
                    </a>
                    {% endif %}
                    &nbsp;
                </div>
            </div>
            <!-- /.box-header -->

            <div class="box-body">
                <dl class="dl-horizontal">
                    <dt>Group</dt>
                    <dd>{{ mhc_details.group }}</dd>
                    <dt>Gender</dt>
                    <dd>{{ mhc_details.get_gender_display }}</dd>
                </dl>
            </div>
            <!-- /.box-body -->

            <div class="box-footer">
            </div>
            <!-- /.box-footer-->
        </div>
        <!-- /.box -->
    </div>
    <!-- /.col -->

    <div class="col-sm-6">
        <!-- MHC alleles box -->
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">
                    <i class="fa fa-list"></i>&nbsp;&nbsp;
                    MHC alleles</h3>

                <div class="pull-right">
                    {% if obj.change_permission %}
                    <a href="{% url 'biological_sample:mhc_allele' obj.pk %}"
                       id="id_mhc_allele_link">
                        <i class="fa fa-pencil fa-lg" title="Edit"></i>
                    </a>
                    {% endif %}
                    &nbsp;
                </div>
            </div>
            <!-- /.box-header -->

            <div class="box-body">
                {% for allele in mhc_alleles %}
                <div class="allele col-sm-6">
                    {{ allele.name }}
                </div>

                {% endfor %}
            </div>
            <!-- /.box-body -->

            <div class="box-footer">
            </div>
            <!-- /.box-footer-->
        </div>
        <!-- /.box -->
    </div>
    <!-- /.col -->
</div>
<!-- /.row -->



<div class="row">

    <div class="col-md-12">


        <!-- Main Tabs -->
        <div class="nav-tabs-custom">

            <ul class="nav nav-tabs" id="tabs">
                <li>
                    <a href="#tab_experiments_details" data-toggle="tab"
                    data-url="{% url 'biological_sample:experiment_details_tabview' obj.pk %}">
                    <h4><i class="fa fa-book"></i>&nbsp;&nbsp;
                    Experiment details</h4></a>
                </li>
                <li>
                    <a href="#tab_genomics" data-toggle="tab"
                    data-url="{% url 'fileset:tabview' obj.pk 'BAM'%}">
                    <h4><i class="fa fa-file"></i>&nbsp;&nbsp;
                    Genomics</h4></a>
                </li>
                {% if genotyping %}
                <li>
                    <a href="#tab_genotyping" data-toggle="tab"
                    data-url="{% url 'genotyping:tabview' obj.pk %}">
                    <h4><i class="fa fa-list-alt"></i>&nbsp;&nbsp;
                    MHC genotyping</h4></a>
                </li>
                {% endif %}
                <li><a href="#tab_personalized_proteome" data-toggle="tab"
                       data-url="{% url 'pps:tabview' obj.pk %}">
                    <h4><i class="fa fa-book"></i>&nbsp;&nbsp;Personalized proteome</h4></a>
                </li>
                <li>
                    <a href="#tab_ms_raw" data-toggle="tab"
                    data-url="{% url 'fileset:tabview' obj.pk 'LC-MS'%}">
                    <h4><i class="fa fa-file"></i>&nbsp;&nbsp;
                    MS raw</h4></a>
                </li>
                <li>
                    <a href="#tab_identification" data-toggle="tab"
                    data-url="{% url 'identification:tabview' obj.pk %}">
                    <h4><i class="fa fa-list-alt"></i>&nbsp;&nbsp;
                    Identification</h4></a>
                </li>
                <li>
                    <a href="#tab_immunopeptidome" data-toggle="tab"
                    data-url="{% url 'immunopeptidome:tabview' obj.pk %}">
                    <h4><i class="fa fa-barcode"></i>&nbsp;&nbsp;
                    Immunopeptidome</h4></a>
                </li>
                <li>
                    <a href="#tab_quantification" data-toggle="tab"
                    data-url="{% url 'fileset:tabview' obj.pk 'PEAKS - features'%}">
                    <h4><i class="fa fa-file"></i>&nbsp;&nbsp;
                    Quantification</h4></a>
                </li>
            </ul>

            <div class="tab-content">
                <div class="tab-pane" id="tab_experiments_details"></div>
                <div class="tab-pane" id="tab_genomics"></div>
                <div class="tab-pane" id="tab_genotyping"></div>
                <div class="tab-pane" id="tab_personalized_proteome"></div>
                <div class="tab-pane" id="tab_ms_raw"></div>
                <div class="tab-pane" id="tab_identification"></div>
                <div class="tab-pane" id="tab_immunopeptidome"></div>
                <div class="tab-pane" id="tab_quantification"></div>
            </div>
            <!-- /.tab-content -->
        </div>
        <!-- nav-tabs-custom -->



    </div>
    <!-- /.col -->
</div>
<!-- /.row -->
<br/><br/>

{% endblock %}


{% block page_js %}
<script src="{% static 'js/tabs.js' %}"></script>
{% endblock %}